spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  
    show-sql: true
    open-in-view: true

# jwt
app:
  jwt:
    secret: ${JWT_SECRET}}     
    #expire after 1 day
    expiration-in-ms: 86400000

authentication:
  internal-api-key: ${INTERNAL_API_KEY}